services:
  fakessh:
    image: honeok/fakessh
    container_name: fakessh
    restart: unless-stopped
    ports:
      - 22:22
    command: /log
    volumes:
      - ./log:/log
    networks:
      - fakessh

networks:
  fakessh:
    driver: bridge